version: "3"
name: mip-voyage
services:
  api:
    container_name: mip-container
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/usr/src/api
    ports:
      - 8050:8000
